# -*- coding: utf-8 -*-
"""Taller_16_Abril.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTaHMacPs9yP7ThOH5v4VuLNselam1_1

# Taller 16 Abril

Optimización — Universidad Nacional de Colombia, Sede Bogotá

## 1. Mezcla de fertilizantes

> Una empresa agricola fabrica dos tipos de fertilizante mezclando tres compuestos quimicos (A, B, C). Tiene disponibles 120 kg de A, 80 kg de B y 150 kg de C por semana. Cada tonelada producida genera una ganancia de \$180 (F1) y \$220 (F2).
>
> | | Compuesto A (kg) | Compuesto B (kg) | Compuesto C (kg) | Ganancia (\$/ton) |
> |---|---|---|---|---|
> | Fertilizante F1 ($x_1$) | 3 | 2 | 5 | 180 |
> | Fertilizante F2 ($x_2$) | 4 | 1 | 3 | 220 |
> | Disponible (kg) | 120 | 80 | 150 | — |
>
> **a)** Define las variables de decision.
> **b)** Formula la funcion objetivo.
> **c)** Plantea todas las restricciones del problema incluyendo no negatividad.
> **d)** Clasifica el modelo como lineal/no lineal y continuo/discreto. Justifica.
"""

# MEZCLA DE FERTILIZANTES

from scipy.optimize import linprog

# --- DATOS DEL PROBLEMA ---
# x1 = toneladas de fertilizante F1
# x2 = toneladas de fertilizante F2
#
# Max Z = 180x1 + 220x2
# linprog minimiza, por eso usamos -Z
c = [-180, -220]

# --- RESTRICCIONES ---
# Compuesto A: 3x1 + 4x2 <= 120
# Compuesto B: 2x1 + 1x2 <= 80
# Compuesto C: 5x1 + 3x2 <= 150
A_ub = [
    [3, 4],
    [2, 1],
    [5, 3],
]
b_ub = [120, 80, 150]

# --- LIMITES DE LAS VARIABLES (x >= 0) ---
bounds = [(0, None), (0, None)]

# --- RESOLVER ---
resultado = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')

x1_opt, x2_opt = resultado.x
Z_opt = -resultado.fun

print("---------- MEZCLA DE FERTILIZANTES ----------")
print(f"Estado: {resultado.message}")
print()
print("[a] Variables de decision:")
print("    x1 = toneladas de fertilizante F1")
print("    x2 = toneladas de fertilizante F2")
print()
print("[b] Funcion objetivo:")
print("    Max Z = 180 x1 + 220 x2")
print()
print("[c] Restricciones:")
print("    3 x1 + 4 x2 <= 120   (Compuesto A)")
print("    2 x1 + 1 x2 <= 80    (Compuesto B)")
print("    5 x1 + 3 x2 <= 150   (Compuesto C)")
print("    x1, x2 >= 0")
print()
print("[d] Clasificacion del modelo:")
print("    Tipo      : lineal")
print("    Variables : continuas")
print()
print("---------- SOLUCION OPTIMA ----------")
print(f"  x1 = {x1_opt:.4f} toneladas de F1")
print(f"  x2 = {x2_opt:.4f} toneladas de F2")
print(f"  Ganancia maxima Z = ${Z_opt:.4f}")
print()
print("---------- VERIFICACION DE RESTRICCIONES ----------")
print(f"  Compuesto A: {3*x1_opt + 4*x2_opt:8.4f}  <= 120")
print(f"  Compuesto B: {2*x1_opt + 1*x2_opt:8.4f}  <= 80")
print(f"  Compuesto C: {5*x1_opt + 3*x2_opt:8.4f}  <= 150")

"""## 2. Produccion semanal de una fabrica

> Una fabrica produce sillas y mesas. La produccion de la semana siguiente depende de la demanda de la semana actual:
>
> $$S_{n+1} = 0.6\,S_n + 0.2\,M_n + 40$$
> $$M_{n+1} = 0.1\,S_n + 0.5\,M_n + 20$$
>
> Donde $S_n$ es el numero de sillas y $M_n$ el de mesas en la semana $n$. Se parte de $S_0 = 200$, $M_0 = 80$.
>
> **a)** Identifica las variables dependientes e independientes.
> **b)** Clasifica el modelo y justifica por que es lineal y discreto.
> **c)** Calcula la produccion de las semanas 1 y 2.
> **d)** ¿Hacia que valores de equilibrio tienden $S_n$ y $M_n$? Plantea el sistema para encontrarlo (no es necesario resolverlo).

"""

# PRODUCCION SEMANAL DE UNA FABRICA

import numpy as np

# --- DATOS DEL PROBLEMA ---
# S_n = numero de sillas producidas en la semana n
# M_n = numero de mesas producidas en la semana n
#
# S_(n+1) = 0.6*S_n + 0.2*M_n + 40
# M_(n+1) = 0.1*S_n + 0.5*M_n + 20

S0 = 200
M0 = 80

# --- MATRIZ DEL SISTEMA ---
A = np.array([
    [0.6, 0.2],
    [0.1, 0.5],
])
b = np.array([40, 20])
x0 = np.array([S0, M0])

# --- CALCULAR SEMANA 1 Y 2 ---
x1 = A @ x0 + b
x2 = A @ x1 + b

# --- EQUILIBRIO ---
# En equilibrio se cumple: x = A*x + b
# (I - A)x = b
equilibrio = np.linalg.solve(np.eye(2) - A, b)

print("---------- PRODUCCION SEMANAL DE UNA FABRICA ----------")
print()
print("[a] Variables del modelo:")
print("    Variable independiente : n (numero de semana)")
print("    Variables dependientes : S_n y M_n")
print()
print("[b] Clasificacion del modelo:")
print("    Tipo      : lineal")
print("    Variables : discretas")
print()
print("[c] Produccion semanas 1 y 2:")
print(f"    Semana 0 -> Sillas = {x0[0]:8.4f} | Mesas = {x0[1]:8.4f}")
print(f"    Semana 1 -> Sillas = {x1[0]:8.4f} | Mesas = {x1[1]:8.4f}")
print(f"    Semana 2 -> Sillas = {x2[0]:8.4f} | Mesas = {x2[1]:8.4f}")
print()
print("[d] Sistema de equilibrio (I - A) x = b :")
print("    0.4 S* - 0.2 M* = 40")
print("   -0.1 S* + 0.5 M* = 20")
print()
print(f"    S* = {equilibrio[0]:.4f} sillas")
print(f"    M* = {equilibrio[1]:.4f} mesas")

"""## 3. Epidemia en una ciudad - Modelo SIS

> En una ciudad de 10,000 habitantes se modela la propagacion de una enfermedad. El modelo SIS divide la poblacion en susceptibles $S(t)$ e infectados $I(t)$. La tasa de nuevos contagios es proporcional al producto $S \cdot I$ y los infectados se recuperan a tasa $\gamma = 0.1$ por dia. La tasa de contagio es $\beta = 0.00003$ por dia.
>
> Como la poblacion total es constante: $S(t) + I(t) = 10{,}000$, el modelo se reduce a:
>
> $$\frac{dI}{dt} = \beta (10{,}000 - I)\,I - \gamma\,I$$
>
> Se inicia con $I(0) = 50$ personas infectadas.
>
> **a)** Identifica las variables y parametros del modelo.
> **b)** Explica por que este modelo es no lineal. Señala el termino responsable.
> **c)** Escribe la condicion inicial.
> **d)** Encuentra los puntos de equilibrio igualando $dI/dt = 0$ (sin resolver la EDO).
> **e)** Interpreta fisicamente cada punto de equilibrio encontrado.

"""

# EPIDEMIA EN UNA CIUDAD

import numpy as np

# --- DATOS DEL PROBLEMA ---
# I(t) = numero de infectados
# S(t) = numero de susceptibles
# Poblacion total: S(t) + I(t) = 10000
#
# dI/dt = beta*(10000 - I)*I - gamma*I

N = 10000
beta = 0.00003
gamma = 0.1
I0 = 50
S0 = N - I0

# --- FUNCION DEL MODELO ---
def dI_dt(I):
    return beta * (N - I) * I - gamma * I

# --- PUNTOS DE EQUILIBRIO ---
# 0 = I * (beta*(N - I) - gamma)
I_eq_1 = 0.0
I_eq_2 = N - (gamma / beta)

S_eq_1 = N - I_eq_1
S_eq_2 = N - I_eq_2

print("---------- EPIDEMIA EN UNA CIUDAD (Modelo SIS) ----------")
print()
print("[a] Variables y parametros:")
print("    Variable dependiente   : I(t) -> infectados")
print("    Variable independiente : t -> tiempo (dias)")
print("    Variable relacionada   : S(t) = 10000 - I(t)")
print(f"    beta  = {beta}  (tasa de contagio)")
print(f"    gamma = {gamma}    (tasa de recuperacion)")
print(f"    N     = {N}   (poblacion total)")
print()
print("[b] Clasificacion y no linealidad:")
print("    Tipo   : no lineal")
print("    Tiempo : continuo")
print("    Termino responsable: beta*(10000 - I)*I  (contiene I^2)")
print()
print("[c] Condicion inicial:")
print(f"    I(0) = {I0:.4f}")
print(f"    S(0) = {S0:.4f}")
print()
print("[d] Puntos de equilibrio (dI/dt = 0):")
print(f"    Equilibrio 1 -> I* = {I_eq_1:8.4f} ")
print(f"    Equilibrio 2 -> I* = {I_eq_2:8.4f} ")
print()
print("[e] Interpretacion fisica:")
print("    Equilibrio 1: libre de enfermedad - la enfermedad desaparece.")
print("    Equilibrio 2: estado endemico - la enfermedad permanece en la ciudad.")

"""## 4. Modelo logistico de pesca

> Una laguna tiene una poblacion de peces que crece logisticamente. Cada año se extraen $H = 80$ peces por pesca controlada. La capacidad maxima de la laguna es $K = 1000$ peces y la tasa de crecimiento intrinseca es $r = 0.4$.
>
> $$P_{n+1} = P_n + r\,P_n\!\left(1 - \tfrac{P_n}{K}\right) - H$$
>
> Se parte de una poblacion inicial de $P_0 = 400$ peces.
>
> **a)** Identifica variables y parametros.
> **b)** Explica por que el modelo es no lineal y discreto.
> **c)** Calcula $P_1$ y $P_2$ (poblacion al final del año 1 y 2).
> **d)** Encuentra el o los puntos de equilibrio del sistema (cuando $P_{n+1} = P_n$). Plantea y resuelve la ecuacion resultante.
> **e)** Interpreta fisicamente los equilibrios obtenidos: ¿que le ocurre a la poblacion si inicia por debajo del equilibrio inestable?

"""

# MODELO LOGISTICO DE PESCA

import numpy as np

# --- DATOS DEL PROBLEMA ---
# P_n = poblacion de peces al final del año n
#
# P_(n+1) = P_n + r*P_n*(1 - P_n/K) - H

r = 0.4
K = 1000
H = 80
P0 = 400

# --- MODELO DISCRETO ---
def siguiente_poblacion(P):
    return P + r * P * (1 - P / K) - H

# --- CALCULAR P1 Y P2 ---
P1 = siguiente_poblacion(P0)
P2 = siguiente_poblacion(P1)

# --- PUNTOS DE EQUILIBRIO ---
# En equilibrio: P_(n+1) = P_n = P*
# r*P*(1 - P/K) - H = 0  =>  (r/K)*P^2 - r*P + H = 0
coeficientes = [r / K, -r, H]
equilibrios = np.roots(coeficientes)
equilibrios = np.sort(np.real_if_close(equilibrios))

P_eq_1 = float(equilibrios[0])
P_eq_2 = float(equilibrios[1])

# --- ESTABILIDAD LOCAL ---
# F'(P) = 1 + r - 2rP/K
def derivada_modelo(P):
    return 1 + r - (2 * r * P / K)

der_eq_1 = derivada_modelo(P_eq_1)
der_eq_2 = derivada_modelo(P_eq_2)

estabilidad_1 = "estable" if abs(der_eq_1) < 1 else "inestable"
estabilidad_2 = "estable" if abs(der_eq_2) < 1 else "inestable"

print("---------- MODELO LOGISTICO DE PESCA ----------")
print()
print("[a] Variables y parametros:")
print("    Variable dependiente   : P_n -> poblacion de peces")
print("    Variable independiente : n -> año")
print(f"    r = {r}   (tasa de crecimiento)")
print(f"    K = {K}   (capacidad maxima)")
print(f"    H = {H}     (cuota de pesca anual)")
print()
print("[b] Clasificacion del modelo:")
print("    Tipo   : no lineal (contiene P_n^2)")
print("    Tiempo : discreto")
print()
print("[c] Poblacion en los años 1 y 2:")
print(f"    Año 0 -> P = {P0:.4f}")
print(f"    Año 1 -> P = {P1:.4f}")
print(f"    Año 2 -> P = {P2:.4f}")
print()
print("[d] Puntos de equilibrio (P_(n+1) = P_n):")
print("    Ecuacion: (r/K)*P^2 - r*P + H = 0")
print(f"    Equilibrio 1: P* = {P_eq_1:.4f}  ({estabilidad_1})")
print(f"    Equilibrio 2: P* = {P_eq_2:.4f}  ({estabilidad_2})")
print()
print("[e] Interpretacion fisica:")
print("    Si la poblacion inicia por debajo del equilibrio inestable,")
print("    la pesca domina y la poblacion tiende a colapsar (extincion).")
print("    Si inicia por encima de ese umbral, tiende al equilibrio estable.")
print()
print("---------- VERIFICACION ----------")
print(f"    F(P*) en {P_eq_1:.4f} = {siguiente_poblacion(P_eq_1):.4f}")
print(f"    F(P*) en {P_eq_2:.4f} = {siguiente_poblacion(P_eq_2):.4f}")